<?php

namespace Modules\Main\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ImageUploadRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'upload'    => 'required|image|between:10,3024',
        ];
    }

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    public function getRedirectUrl()
    {
        return parent::getRedirectUrl(); // TODO: Change the autogenerated stub
    }


}
